version: '3'
services:
   nodeappmss:
      image: lokeshsdockerhub/nodeappmss:VERSION
      ports:
       - 9981:9981
      networks:
       - nodeappmssbridge
networks:
  nodeappmssbridge:
     driver: bridge
